sudo: required
language: node_js
node_js: 8
addons:
  firefox: latest
  chrome: stable
before_install:
  - npm install -g polymer-cli
  - polymer install
script:
  - polymer lint
  - 'xvfb-run polymer test --module-resolution=node --npm -l firefox,chrome'

